<?php

namespace AppBundle\Repository;

/**
 * PostStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostStateRepository extends \Doctrine\ORM\EntityRepository
{
}
